"""add foreignkey between albummodel and usermodel 

Revision ID: eff1224db90c
Revises: 4899c93074df
Create Date: 2022-08-17 13:35:43.935310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff1224db90c'
down_revision = '4899c93074df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albums', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_column('albums', 'user_id')
    # ### end Alembic commands ###
